development:
  adapter: postgresql
  encoding: unicode
  database: spree_db_development
  pool: 5
  username: shaheryar
  password: 
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: spree_db_test
  pool: 5
  username: shaheryar
  password: 
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: spree_db_production
  pool: 5
  username: shaheryar
  password: 
  host: localhost